name: build-and-publish-backend

run-name: ${{github.actor}} is building and publishing backend
on: [push]

env:
  BRANCH_NAME: ${GITHUB_REF##*/}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example.backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: package with maven ${{env.BRANCH_NAME}}
        run: mvn package -Djar.name=helloworld-backend-${{env.BRANCH_NAME}}
      - name: Publish build artifact
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-jar
          path: ./target/helloworld-backend-*.jar
      - name: upload to s3 bucket
        run: aws s3 cp ./target/helloworld-backend-${{env.BRANCH_NAME}}.jar s3://example-jar-backend