name: build-publish-deploy-destroy

run-name: ${{github.actor}} is building and publishing backend
on: [push]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example.backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: package with maven ${{env.BRANCH_NAME}}
        run: mvn package -Djar.name=helloworld-backend-${{env.BRANCH_NAME}}
      - name: upload to s3 bucket
        run: aws s3 cp ./target/helloworld-backend-${{env.BRANCH_NAME}}.jar s3://example-jar-backend
  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-cdk
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Change S3 bucket URL in user-data
        run: sed -i "s/NAME_OF_JAR_TO_DEPLOY/helloworld-backend-${{env.BRANCH_NAME}}/g" ./scripts/backend.sh
      - name: Synth stack
        run: npm run cdk -- synth BackendExampleStack
      - name: Deploy stack
        run: npm run cdk -- deploy BackendExampleStack --require-approval never --outputs-file backend-outputs.json
      - name: Upload outputs file
        uses: actions/upload-artifact@v3
        with:
          name: backend-outputs.json
          path: aws-cdk/backend-outputs.json
  build-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-frontend
    - uses: actions/checkout@v3
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
          node-version: 16
    - name: Install dependencies
      run: npm install

